"""
-------------------------------------------------------------------------------

    Written by Thomas Munzer (tmunzer@juniper.net)
    Github repository: https://github.com/tmunzer/Mist_library/

    This script is licensed under the MIT License.

-------------------------------------------------------------------------------

Python script to compare two different version of summaries generated by the
export_org_events.py script.
This can be used to easily detect new sites referenced.

-------
Options:
-h, --help          display this help
-n, --new=          latest export file
-o, --old=          oldest export file

-------
Examples:
python3 ./compare_org_events_summary \
    -n org_events_summary_2024-09-08T23.35.51.csv
    -o org_events_summary_2024-09-07T23.31.25.csv
        
"""

#### IMPORTS ####
import sys
import csv
import getopt
import datetime

def _load_data(file:str):
    #try:
        with open(file, 'r') as f:
            data = []
            rows = csv.reader(f, delimiter=",")
            i = 0
            for row in rows:
                i+=1
                if i > 2:
                    data.append(row)
            return data
    # except:
    #     print(f"Error: Unable to read {file}")
    #     sys.exit(1)

def _compare(new:str, old:str):
    new_data = _load_data(new)
    old_data = _load_data(old)
    diff = []
    for d in new_data:
        if d not in old_data:
            diff.append(d)
    return diff

def _save(new:str, old: str, data:list):
    filename = new.replace("summary", "diff")
    with open(filename, "w") as f:
        csv_writer = csv.writer(f)
        csv_writer.writerow([f"#compare between {new} and {old}"])
        csv_writer.writerow(["#site","link"])
        for r in data:
            csv_writer.writerow(r)

def start(
    new: str,
    old: str
):
    if not new:
        print("Error: missing new file parameter")
    if not old:
        print("Error: missing old file parameter")
    diff = _compare(new, old)
    _save(new, old, diff)
    print(diff)    

def usage(message: str = None):
    """Function to display Help"""
    print(
        f"""
-------------------------------------------------------------------------------

    Written by Thomas Munzer (tmunzer@juniper.net)
    Github repository: https://github.com/tmunzer/Mist_library/

    This script is licensed under the MIT License.

-------------------------------------------------------------------------------

Python script to compare two different version of summaries generated by the
export_org_events.py script.
This can be used to easily detect new sites referenced.

-------
Options:
-h, --help          display this help
-n, --new=          latest export file
-o, --old=          oldest export file

-------
Examples:
Examples:
python3 ./compare_org_events_summary \
    -n org_events_summary_2024-09-08T23.35.51.csv
    -o org_events_summary_2024-09-07T23.31.25.csv
        
    """
    )
    if message:
        print(f"ERROR: {message}")
    sys.exit(0)


#####################################################################
#### SCRIPT ENTRYPOINT ####
if __name__ == "__main__":
    try:
        opts, args = getopt.getopt(
            sys.argv[1:],
            "hn:o:",
            [
                "help",
                "new=",
                "old=",
            ],
        )
    except getopt.GetoptError as err:
        print(err)
        usage()

    NEW = None
    OLD = None
    for o, a in opts:  # type: ignore
        if o in ["-h", "--help"]:
            usage()
        elif o in ["-n", "--new"]:
            NEW = a
        elif o in ["-o", "--old"]:
            OLD = a
        else:
            assert False, "unhandled option"

   
    start(NEW, OLD)
